<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit.Analyzers" />
        <PackageReference Include="NUnit3TestAdapter" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\Duel.Shared\Duel.Shared.csproj" />
      <ProjectReference Include="..\..\Engine\Duel.Modules.Engine\Duel.Modules.Engine.csproj" />
      <ProjectReference Include="..\Duel.Modules.Lobby\Duel.Modules.Lobby.csproj" />
    </ItemGroup>

</Project>
